BEGIN {
S["am__EXEEXT_FALSE"]=""
S["am__EXEEXT_TRUE"]="#"
S["LTLIBOBJS"]=""
S["LIBOBJS"]=""
S["AM_CXXFLAGS"]=""
S["AM_CPPFLAGS"]=" -I$(top_srcdir)/CxxHead -I$(top_builddir)/CxxHead -DDATA_PATH=${datarootdir} -DQCDNUM_VERSION=18-00-00 "
S["CXXCPP"]="/u/local/compilers/gcc/4.9.3/bin/g++ -E"
S["LT_SYS_LIBRARY_PATH"]=""
S["OTOOL64"]=""
S["OTOOL"]=""
S["LIPO"]=""
S["NMEDIT"]=""
S["DSYMUTIL"]=""
S["MANIFEST_TOOL"]=":"
S["RANLIB"]="ranlib"
S["ac_ct_AR"]="ar"
S["AR"]="ar"
S["DLLTOOL"]="false"
S["OBJDUMP"]="objdump"
S["LN_S"]="ln -s"
S["NM"]="/bin/nm -B"
S["ac_ct_DUMPBIN"]=""
S["DUMPBIN"]=""
S["LD"]="/bin/ld -m elf_x86_64"
S["FGREP"]="/bin/grep -F"
S["EGREP"]="/bin/grep -E"
S["GREP"]="/bin/grep"
S["SED"]="/bin/sed"
S["LIBTOOL"]="$(SHELL) $(top_builddir)/libtool"
S["AM_FFLAGS"]=""
S["F77"]="gfortran"
S["FFLAGS"]=" -O3  -Iinc"
S["am__fastdepCC_FALSE"]="#"
S["am__fastdepCC_TRUE"]=""
S["CCDEPMODE"]="depmode=gcc3"
S["ac_ct_CC"]="/u/local/compilers/gcc/4.9.3/bin/gcc"
S["CFLAGS"]="-g -O2"
S["CC"]="/u/local/compilers/gcc/4.9.3/bin/gcc -std=gnu11"
S["FCLIBS"]=" -L/u/local/compilers/gcc/4.9.3/lib64/../lib64 -L/u/local/compilers/gcc/4.9.3/lib/../lib64 -L/u/local/compilers/gcc/4.9.3/lib/gcc/x86_64-unknown-lin"\
"ux-gnu/4.9.3 -L/u/local/compilers/gcc/4.9.3/lib/gcc/x86_64-unknown-linux-gnu/4.9.3/../../../../lib64 -L/lib/../lib64 -L/usr/lib/../lib64 -L/u/local/"\
"compilers/gcc/4.9.3/lib64 -L/u/local/compilers/gcc/4.9.3/lib -L/u/local/compilers/gcc/4.9.3/lib/gcc/x86_64-unknown-linux-gnu/4.9.3/../../.. -lgfortr"\
"an -lm -lquadmath"
S["host_os"]="linux-gnu"
S["host_vendor"]="pc"
S["host_cpu"]="x86_64"
S["host"]="x86_64-pc-linux-gnu"
S["build_os"]="linux-gnu"
S["build_vendor"]="pc"
S["build_cpu"]="x86_64"
S["build"]="x86_64-pc-linux-gnu"
S["ac_ct_FC"]="gfortran"
S["FCFLAGS"]="-O3  -Iinc"
S["FC"]="gfortran"
S["am__fastdepCXX_FALSE"]="#"
S["am__fastdepCXX_TRUE"]=""
S["CXXDEPMODE"]="depmode=gcc3"
S["am__nodep"]="_no"
S["AMDEPBACKSLASH"]="\\"
S["AMDEP_FALSE"]="#"
S["AMDEP_TRUE"]=""
S["am__include"]="include"
S["DEPDIR"]=".deps"
S["OBJEXT"]="o"
S["EXEEXT"]=""
S["ac_ct_CXX"]=""
S["CPPFLAGS"]=""
S["LDFLAGS"]=""
S["CXXFLAGS"]="-g -O2"
S["CXX"]="/u/local/compilers/gcc/4.9.3/bin/g++"
S["MAINT"]="#"
S["MAINTAINER_MODE_FALSE"]=""
S["MAINTAINER_MODE_TRUE"]="#"
S["AM_BACKSLASH"]="\\"
S["AM_DEFAULT_VERBOSITY"]="0"
S["AM_DEFAULT_V"]="$(AM_DEFAULT_VERBOSITY)"
S["AM_V"]="$(V)"
S["CSCOPE"]="cscope"
S["ETAGS"]="etags"
S["CTAGS"]="ctags"
S["am__untar"]="$${TAR-tar} xf -"
S["am__tar"]="$${TAR-tar} chof - \"$$tardir\""
S["AMTAR"]="$${TAR-tar}"
S["am__leading_dot"]="."
S["SET_MAKE"]=""
S["AWK"]="gawk"
S["mkdir_p"]="$(MKDIR_P)"
S["MKDIR_P"]="/bin/mkdir -p"
S["INSTALL_STRIP_PROGRAM"]="$(install_sh) -c -s"
S["STRIP"]="strip"
S["install_sh"]="${SHELL} /u/home/m/maxzhang/project-zkang/Nuclear-TMDs/AAKTXZ2023/QCDNUM/qcdnum-18-00-00/install-sh"
S["MAKEINFO"]="${SHELL} '/u/home/m/maxzhang/project-zkang/Nuclear-TMDs/AAKTXZ2023/QCDNUM/qcdnum-18-00-00/missing' makeinfo"
S["AUTOHEADER"]="${SHELL} '/u/home/m/maxzhang/project-zkang/Nuclear-TMDs/AAKTXZ2023/QCDNUM/qcdnum-18-00-00/missing' autoheader"
S["AUTOMAKE"]="${SHELL} '/u/home/m/maxzhang/project-zkang/Nuclear-TMDs/AAKTXZ2023/QCDNUM/qcdnum-18-00-00/missing' automake-1.16"
S["AUTOCONF"]="${SHELL} '/u/home/m/maxzhang/project-zkang/Nuclear-TMDs/AAKTXZ2023/QCDNUM/qcdnum-18-00-00/missing' autoconf"
S["ACLOCAL"]="${SHELL} '/u/home/m/maxzhang/project-zkang/Nuclear-TMDs/AAKTXZ2023/QCDNUM/qcdnum-18-00-00/missing' aclocal-1.16"
S["VERSION"]="18-00-00"
S["PACKAGE"]="qcdnum"
S["CYGPATH_W"]="echo"
S["am__isrc"]=""
S["INSTALL_DATA"]="${INSTALL} -m 644"
S["INSTALL_SCRIPT"]="${INSTALL}"
S["INSTALL_PROGRAM"]="${INSTALL}"
S["target_alias"]=""
S["host_alias"]=""
S["build_alias"]=""
S["LIBS"]=""
S["ECHO_T"]=""
S["ECHO_N"]="-n"
S["ECHO_C"]=""
S["DEFS"]="-DHAVE_CONFIG_H"
S["mandir"]="${datarootdir}/man"
S["localedir"]="${datarootdir}/locale"
S["libdir"]="${exec_prefix}/lib"
S["psdir"]="${docdir}"
S["pdfdir"]="${docdir}"
S["dvidir"]="${docdir}"
S["htmldir"]="${docdir}"
S["infodir"]="${datarootdir}/info"
S["docdir"]="${datarootdir}/doc/${PACKAGE_TARNAME}"
S["oldincludedir"]="/usr/include"
S["includedir"]="${prefix}/include"
S["runstatedir"]="${localstatedir}/run"
S["localstatedir"]="${prefix}/var"
S["sharedstatedir"]="${prefix}/com"
S["sysconfdir"]="${prefix}/etc"
S["datadir"]="${datarootdir}"
S["datarootdir"]="${prefix}/share"
S["libexecdir"]="${exec_prefix}/libexec"
S["sbindir"]="${exec_prefix}/sbin"
S["bindir"]="${exec_prefix}/bin"
S["program_transform_name"]="s,x,x,"
S["prefix"]="/u/home/m/maxzhang/project-zkang"
S["exec_prefix"]="${prefix}"
S["PACKAGE_URL"]=""
S["PACKAGE_BUGREPORT"]="h24@nikhef.nl"
S["PACKAGE_STRING"]="QCDNUM 18-00-00"
S["PACKAGE_VERSION"]="18-00-00"
S["PACKAGE_TARNAME"]="qcdnum"
S["PACKAGE_NAME"]="QCDNUM"
S["PATH_SEPARATOR"]=":"
S["SHELL"]="/bin/sh"
S["am__quote"]=""
  for (key in S) S_is_set[key] = 1
  FS = ""

}
{
  line = $ 0
  nfields = split(line, field, "@")
  substed = 0
  len = length(field[1])
  for (i = 2; i < nfields; i++) {
    key = field[i]
    keylen = length(key)
    if (S_is_set[key]) {
      value = S[key]
      line = substr(line, 1, len) "" value "" substr(line, len + keylen + 3)
      len += length(value) + length(field[++i])
      substed = 1
    } else
      len += 1 + keylen
  }

  print line
}

